### PR TITLE
Added Hacktoberfest Finder as a search engine

### PR DESCRIPTION
**Pull request by damcclean**
This PR adds [Hacktoberfest Finder](https://hacktoberfest-finder.netlify.app/), a small web app I've been working on the past few years with various open-source contributors that helps developers find issues to work on during Hacktoberfest.

### CODE REVIEW

**Comment by koppor** [comment]
Thank you for the site.

I checked the projects listed. Most of them are very new (3 days) and are playground projects. Examples:

- https://github.com/ACM-VIT/libground
- https://github.com/coderobe/callsite.jar

May I ask that your site only lists repositories created before 2020-09-01?

Side note: Maybe I should write a GraphQL query to query all new projects with "hacktoberfest" label to be able to submit them to https://hacktoberfest.digitalocean.com/report.

**Comment by koppor** [comment]
Refs https://github.com/damcclean/hacktoberfest-finder/issues/203

**Comment by damcclean** [comment]
I've commented on the related issue on my Hacktoberfest Finder repository. 

Sorry for taking such a long time to respond. Completely forgot about this PR.

**Comment by koppor** [comment]
I fixed the alphabetical ordering required by our CONTRIBUTING.md. Now, ti tis good to go.

**Pull request merged**
