### PR TITLE
Added a cute webpage for the match of the pets

### PR DESCRIPTION
**Pull request by mihikachh22**
Hey there,
I have made a web page that decides who is your perfect pet match and added that.

### CODE REVIEW

**Comment by mattjegan** [comment]
Hi, thanks for the PR however this repository is aiming to be a document to link people to hacktoberfest related content and projects that are involved. It looks like you are trying to include a whole project, for this I would look at a repo like https://github.com/vijaygupta18/Hacktober-2020

**Comment by mihikachh22** [comment]
So, does that mean that it will not be included as a PR for hacktoberfest?
Please tell ASAP

**Comment by koppor** [comment]
@mihikachh22 Before we can answer your question, please write us a small markdown file elaborating the core rules and aims of hacktoberfest. Include a recent training video and elaborate on how it influences you and your progress.

**Comment by mihikachh22** [comment]
Hello there,
These are some objectives of Hactoberfest
To earn our Hacktoberfest tee or tree reward, we must register and make
four valid pull requests (PRs) between October 1-31 (in any time zone). PRs
can be made to participating public repos on GitHub, those that have the
Hacktoberfest topic. If a maintainer reports your pull request as spam or
behavior not in line with the project’s code of conduct, we will be
ineligible to participate. This year, the first 70,000 participants who
successfully complete the challenge will be eligible to receive a prize.

https://youtu.be/0BV1QCl8Az0

Ever since I watched this tutorial, I aimed to contribute in open source.
By contributing to a repository, we help others as well as build are
skills. Much improvements are added in our process of thinking and making
of our own project. This is the first time, I am a part of Hacktoberfest
and want to win this challenge by contributing to the fullest.

**Pull request closed without merging**
